import "dotenv/config"

const {
  PORT,
  NODE_ENV,
  JWT_SECRET,
  RESEND_API_KEY,
  EMAIL_FROM,
  EMAIL_FROM_NAME,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_CLOUD_KEY,
  CLOUDINARY_CLOUD_SECRET,
  MONGO_URI,
  CLIENT_URL,
  ARCJET_KEY,
  ARCJET_ENV,
} = process.env

export const ENV = {
  PORT: PORT || 3000,
  NODE_ENV,
  JWT_SECRET,
  RESEND_API_KEY,
  EMAIL_FROM,
  EMAIL_FROM_NAME,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_CLOUD_KEY,
  CLOUDINARY_CLOUD_SECRET,
  MONGO_URI,
  CLIENT_URL,
  ARCJET_KEY,
  ARCJET_ENV,
}
